#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# repro spike P0-B — B2 : bring up the production-like spike environment.
#
#   ./up.sh                 # full topology (needs src/spike/app/ from B1)
#   ./up.sh --infra-only    # spike-postgres + spike-redis only (Wave-1 degraded
#                           # mode while B1 is still writing src/spike/app/)
#
# Creates the LONG-LIVED external network if absent. That network is never
# destroyed by destroy.sh — see docker-compose.spike.yml header.
# ---------------------------------------------------------------------------
set -euo pipefail
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib/common.sh"

INFRA_ONLY=0
RUN_ID_ARG=""
while [ $# -gt 0 ]; do
  case "$1" in
    --infra-only) INFRA_ONLY=1 ;;
    --run-id)     RUN_ID_ARG="${2:-}"; shift ;;
    *) die "unknown arg: $1" ;;
  esac
  shift
done

mkdir -p "${ARTIFACT_DIR}" "${CANARY_LOG_DIR}" "${EVIDENCE_DIR}"

# --- run identity ----------------------------------------------------------
RUN_ID="${RUN_ID_ARG:-r$(date -u +%Y%m%dT%H%M%SZ)}"
# Per-run nonce. Two purposes:
#   1. distinguishes two runs that share a run_id prefix;
#   2. seeds the per-run Postgres password, so environment secrets ROTATE per
#      run (protects A-05). NOTE: this rotates the ENVIRONMENT secret, it does
#      NOT satisfy the "revoke/rotate destroy credential" clause of exit
#      criteria B2(d) — the docker socket has no token to revoke. Declared in
#      the §5.2 shortcut ledger.
NONCE="$(head -c 12 /dev/urandom | od -An -tx1 | tr -d ' \n')"

# --- the long-lived external network --------------------------------------
if docker network inspect "${SPIKE_NETWORK}" >/dev/null 2>&1; then
  log "network ${SPIKE_NETWORK} already present (long-lived, reused)"
else
  log "creating long-lived external network ${SPIKE_NETWORK}"
  docker network create \
    --label "${LABEL_PERSISTENT_KEY}=true" \
    --label "${LABEL_ROLE_KEY}=network" \
    --label "repro.spike.phase=P0-B" \
    --subnet "${SPIKE_NETWORK_SUBNET}" \
    "${SPIKE_NETWORK}" >/dev/null
fi

# --- render the per-run env file ------------------------------------------
cat > "${RUN_ENV_FILE}" <<EOF
# generated by up.sh — DO NOT COMMIT (src/spike/**/artifacts/ is gitignored)
SPIKE_RUN_ID=${RUN_ID}
SPIKE_NONCE=${NONCE}
SPIKE_NETWORK=${SPIKE_NETWORK}
SPIKE_APP_PORT=${SPIKE_APP_PORT}
SPIKE_STUB_PORT=${SPIKE_STUB_PORT}
SPIKE_PG_USER=spike
SPIKE_PG_PASSWORD=spk_${NONCE}
SPIKE_PG_DATABASE=spikedb
HOST_BIND_ADDR=${HOST_BIND_ADDR}
HOST_APP_PORT=${HOST_APP_PORT}
HOST_STUB_PORT=${HOST_STUB_PORT}
HOST_PG_PORT=${HOST_PG_PORT}
HOST_REDIS_PORT=${HOST_REDIS_PORT}
EOF
log "run env written to ${RUN_ENV_FILE} (run_id=${RUN_ID} nonce=${NONCE})"

# Read it straight back so SPIKE_PG_USER / _PASSWORD / _DATABASE exist as shell
# variables for the seed step below. Sourcing the file we just wrote (instead of
# keeping a second copy in shell state) guarantees the seed uses EXACTLY the
# credentials compose injects — one source of truth, no drift.
load_run_env

# --- fail-closed on port contention ---------------------------------------
# If anything already holds one of our host ports, we do NOT stop it and we do
# NOT pick a different port silently. We refuse. A silently-remapped port makes
# the canary's later re-claim of the SAME port impossible to interpret.
for p in "${HOST_APP_PORT}" "${HOST_STUB_PORT}" "${HOST_PG_PORT}" "${HOST_REDIS_PORT}"; do
  if lsof -nP -iTCP:"${p}" -sTCP:LISTEN >/dev/null 2>&1; then
    lsof -nP -iTCP:"${p}" -sTCP:LISTEN >&2 || true
    die "host port ${p} is already held. FAIL-CLOSED: not stopping the holder, \
not remapping. Free it manually or override HOST_*_PORT."
  fi
done

dc() {
  docker compose \
    --env-file "${RUN_ENV_FILE}" \
    -f "${INFRA_DIR}/docker-compose.spike.yml" \
    -p "${COMPOSE_PROJECT_ENV}" "$@"
}

APP_IMAGE="repro-spike-app:${RUN_ID}"
FLAGS_VOLUME="repro-spike-flags-${RUN_ID}"

if [ "${INFRA_ONLY}" -eq 1 ]; then
  log "DEGRADED MODE --infra-only: only spike-postgres + spike-redis"
  log "  spike-app / spike-httpstub stay DECLARED in compose but are not started,"
  log "  and neither the flag file nor the DB seed is provisioned."
  dc up -d --wait spike-postgres spike-redis
  log "environment up (degraded). label scope: ${LABEL_ENV_KEY}=${RUN_ID}"
  docker ps --filter "label=${LABEL_ENV_KEY}=${RUN_ID}" \
    --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}' >&2
  exit 0
fi

# ---------------------------------------------------------------------------
# Ordering below is load-bearing. spike-app fails its FIRST request unless BOTH
# of these are provisioned before it starts:
#   INT-1  the flag file must EXIST on the flags volume, else every request 500s
#          with FlagError (B1 flags.js reads SPIKE_FLAG_FILE on every request);
#   INT-2  the schema must EXIST in Postgres, else every pg query fails.
# Neither is something the app self-provisions, and neither belongs to B1 —
# they live exactly on the infra/app boundary, which is this file's job.
# ---------------------------------------------------------------------------

# 1. Build the shared image.
log "step 1/6 build ${APP_IMAGE}"
dc build spike-app

# 2. `create` (not `up`): this materialises the NAMED, LABELLED volumes without
#    starting anything, so step 3 can write into the flags volume before any
#    container that reads it exists. Creating the volume by hand instead would
#    race with compose's own volume bookkeeping.
log "step 2/6 create containers + labelled volumes (nothing started yet)"
dc create

# 3. INT-1 — seed the flag file onto the flags volume.
#    Source is the default shipped INSIDE the image by B1 at
#    /srv/spike/flags/spike-flags.default.json. We copy rather than bind-mount
#    B1's working tree: the volume is labelled and therefore inside destroy's
#    scope, so the flag file dies with the environment like everything else.
log "step 3/6 provisioning /var/spike/flags/flags.json on volume ${FLAGS_VOLUME}"
docker run --rm \
  -v "${FLAGS_VOLUME}:/var/spike/flags" \
  --entrypoint /bin/sh \
  "${APP_IMAGE}" \
  -c 'set -eu
      test -f /srv/spike/flags/spike-flags.default.json || {
        echo "image is missing /srv/spike/flags/spike-flags.default.json" >&2; exit 66; }
      cp /srv/spike/flags/spike-flags.default.json /var/spike/flags/flags.json
      chmod 0644 /var/spike/flags/flags.json'

# Read it back from the volume — provisioning that is not verified is a guess.
log "step 3/6 verifying flag file content as the app will see it:"
# Deliberately minimal quoting: the JS takes its path from argv, so there are no
# nested quotes to get wrong. It re-implements B1's flags.js acceptance test
# (readable + parses + flat object) so a bad file fails HERE, at provisioning
# time, rather than as a 500 on the first request.
docker run --rm \
  -v "${FLAGS_VOLUME}:/var/spike/flags:ro" \
  --entrypoint node \
  "${APP_IMAGE}" \
  -e 'var j=JSON.parse(require("node:fs").readFileSync(process.argv[1],"utf8"));
      if(j===null||typeof j!=="object"||Array.isArray(j)){throw new Error("flags.json is not a flat JSON object");}
      console.log("flags.json OK -> "+JSON.stringify(j));' \
  /var/spike/flags/flags.json >&2

# 4. Data tier first, and WAIT for it to be healthy — the seed cannot connect
#    to a Postgres that is still doing initdb.
log "step 4/6 starting spike-postgres + spike-redis"
dc up -d --wait spike-postgres spike-redis

# 5. INT-2 — one-shot schema + synthetic reference data.
#    Runs as its own container on the spike network so it resolves the CT-3 DNS
#    name spike-postgres exactly as the app will. B1's seed.js is idempotent
#    (CREATE TABLE IF NOT EXISTS, upserts, TRUNCATE ... RESTART IDENTITY), so a
#    re-run is safe and leaves a deterministic starting state.
log "step 5/6 seeding schema + SYNTHETIC reference data (G2: no production data)"
docker run --rm \
  --network "${SPIKE_NETWORK}" \
  --label "${LABEL_ENV_KEY}=${RUN_ID}" \
  --label "${LABEL_ROLE_KEY}=seed" \
  -e SPIKE_ENTRYPOINT=seed \
  -e SPIKE_RUN_ID="${RUN_ID}" \
  -e SPIKE_PG_HOST=spike-postgres \
  -e SPIKE_PG_PORT=5432 \
  -e SPIKE_PG_USER="${SPIKE_PG_USER}" \
  -e SPIKE_PG_PASSWORD="${SPIKE_PG_PASSWORD}" \
  -e SPIKE_PG_DATABASE="${SPIKE_PG_DATABASE}" \
  "${APP_IMAGE}"

# 6. Everything else.
log "step 6/6 starting spike-httpstub + spike-app"
dc up -d --wait

log "environment up. label scope: ${LABEL_ENV_KEY}=${RUN_ID}"
docker ps --filter "label=${LABEL_ENV_KEY}=${RUN_ID}" \
  --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}' >&2
